# Rappels

Filtrage

In [19]:
import numpy as np 
import pandas 
df = pandas.DataFrame(np.arange(16).reshape(4,4), index=["Ohio", "Colorado", "Utah", "New York"], columns=["one", "two", "three", "four"])
df

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [20]:
# Selectionner une sous-partie du DF
# 1. ligne Colorado, colonnes "two" et "three"
# obtenu avec .loc[] : requête par nom
df.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [21]:
# 2. toutes les lignes, colonnes "two" et "three"
df.loc[:, ["two", "three"]]

          two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [22]:
# 3. toutes les lignes, colonnes "two" à "four"
df.loc[:, "two": "four"]

          two  three  four
Ohio        1      2     3
Colorado    5      6     7
Utah        9     10    11
New York   13     14    15

In [23]:
# 4. lignes jusqu'a "Utah", colonne "two"
df.loc[:"Utah", "two"]

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

In [24]:
# Selectionner une sous-partie du DF: une seule ligne
df.loc["Utah",:]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [25]:
# Selectionner une sous-partie du DF : une seule colonne
df.loc[:,"one"]

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int64

In [26]:
# Selectionner une sous-partie du DF
# Traiter les cas plus complexes
df.loc[lambda df: df.index.str.len() > 4]

          one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

Données manquantes

In [27]:
string_data = pandas.Series(["aarggfx", "artichaut", np.nan, "avocado"])
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [28]:
# Par défaut, .dropna() supprime des lignes ("axis = 0")
df_with_na = pandas.DataFrame(
    [[1, np.nan], [2, 3], [np.nan, 7]], 
    index= ["a", "b", "c"], 
    columns = ["A", "B"])
df_with_na

     A    B
a  1.0  NaN
b  2.0  3.0
c  NaN  7.0

In [29]:
df_with_na.dropna()

     A    B
b  2.0  3.0

In [30]:
# Il peut aussi supprimer des colonnes
df_with_na.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [a, b, c]

In [31]:
# .fillna()
value_to_replace_na_with = 0
df_with_na.fillna(value_to_replace_na_with)

     A    B
a  1.0  0.0
b  2.0  3.0
c  0.0  7.0

In [32]:
# .fillna() avec dict
value_to_replace_na_with = {"A":1, "B":3}
df_with_na.fillna(value_to_replace_na_with)

     A    B
a  1.0  3.0
b  2.0  3.0
c  1.0  7.0

Exercices

In [33]:
# Lire les données du Titanic
# Créer un dataframe avec 100 lignes
from pandas import read_csv
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df_titanic = read_csv(url)
df_titanic
# Filtrer le df pour n'obtenir que les hommes qui ont payé plus de 50$
# Combien y en a-t-il ? 


df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [34]:
df_titanic.loc[(df_titanic["Fare"] > 50) & (df_titanic["Sex"] == "male")].shape[0]

73

In [35]:
# Filtrer le df pour n'obtenir que les femmes de moins de 18 ans
# Combien y en a-t-il ? 
df_titanic.loc[(df_titanic["Age"] < 18) & (df_titanic["Sex"] == "female")].shape

(55, 12)

In [36]:
# Remplacer les valeurs manquantes de la colonne prix par le prix moyen, et les lieux d'embarquement manquants par "C"
# Est-il possible de faire cela en un seul appel ? 
df_titanic["Embarked"].fillna("C", inplace = True)
df_titanic["Fare"].fillna(df_titanic["Fare"].mean(), inplace = True)

/var/folders/fn/840kfjnd1f3cn2f5lqxn6ymr0000gp/T/ipykernel_85108/3722107139.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_titanic["Embarked"].fillna("C", inplace = True)
/var/folders/fn/840kfjnd1f3cn2f5lqxn6ymr0000gp/T/ipykernel_85108/3722107139.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_titanic["Fare"].fillna(df_titanic["Fare"].mean(), inplace = True)

In [37]:
df_titanic.fillna({"Embarked" : "C"}, inplace = True)
df_titanic.fillna({"Fare" : df_titanic["Fare"].mean()}, inplace = True)

In [38]:
df_titanic.fillna({"Embarked" : "C", "Fare" : df_titanic["Fare"].mean()}, inplace = True)

In [39]:
# Bonus
# Supprimer les lignes où l'âge est manquant
df_titanic.dropna(subset="Age", inplace=True)

In [40]:
# Bonus
# Créer une fonction qui effectue les opérations des trois cellules précédentes
def clean_df(df: pandas.DataFrame) -> pandas.DataFrame:
    return (df.loc[(df["Age"] < 18)& (df["Sex"] == "female")]
    .fillna({"Embarked" : "C", "Fare" : df["Fare"].mean()})
    .dropna(subset="Age"))

    
clean_df(df_titanic)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.00,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
71,72,0,3,"Goodwin, Miss. Lillian Amy",female,16.00,5,2,CA 2144,46.9000,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
111,112,0,3,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C
114,115,0,3,"Attalah, Miss. Malake",female,17.00,0,0,2627,14.4583,NaN,C
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
147,148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.00,2,2,W./C. 6608,34.3750,NaN,S
156,157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.00,0,0,35851,7.7333,NaN,Q
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,NaN,S
205,206,0,3,"Strom, Miss. Telma Matilda",female,2.00,0,1,347054,10.4625,G6,S
208,209,1,3,"Carr, Miss. Helen ""Ellen""",female,16.00,0,0,367231,7.7500,NaN,Q
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,31.3875,NaN,S
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,NaN,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
329,330,1,1,"Hippach, Miss. Jean Gertrude",female,16.00,0,1,111361,57.9792,B18,C
374,375,0,3,"Palsson, Miss. Stina Viola",female,3.00,3,1,349909,21.0750,NaN,S
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C
389,390,1,2,"Lehmann, Miss. Bertha",female,17.00,0,0,SC 1748,12.0000,NaN,C
419,420,0,3,"Van Impe, Miss. Catharina",female,10.00,0,2,345773,24.1500,NaN,S
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
446,447,1,2,"Mellinger, Miss. Madeleine Violet",female,13.00,0,1,250644,19.5000,NaN,S
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.00,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,NaN,S
504,505,1,1,"Maioni, Miss. Roberta",female,16.00,0,0,110152,86.5000,B79,S
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,NaN,S
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,26.2500,NaN,S
541,542,0,3,"Andersson, Miss. Ingeborg Constanzia",female,9.00,4,2,347082,31.2750,NaN,S
542,543,0,3,"Andersson, Miss. Sigrid Elisabeth",female,11.00,4,2,347082,31.2750,NaN,S
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S
634,635,0,3,"Skoog, Miss. Mabel",female,9.00,3,2,347088,27.9000,NaN,S
642,643,0,3,"Skoog, Miss. Margit Elizabeth",female,2.00,3,2,347088,27.9000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
691,692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,NaN,C
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,33.0000,NaN,S
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,NaN,S
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.00,0,0,364516,12.4750,NaN,S
780,781,1,3,"Ayoub, Miss. Banoura",female,13.00,0,0,2687,7.2292,NaN,C
781,782,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.00,1,0,17474,57.0000,B20,S
813,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.00,4,2,347082,31.2750,NaN,S
830,831,1,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.00,1,0,2659,14.4542,NaN,C
852,853,0,3,"Boulos, Miss. Nourelain",female,9.00,1,1,2678,15.2458,NaN,C
853,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.00,0,0,2667,7.2250,NaN,C

In [43]:
# Bonus : filtrage avancé
# Filtrer le df suivant pour ne garder que les lignes où le prénom commence par un "A"
data = {"prenom" : ["Anna", "Ben", "Camille"], "poste": ["DE", "DE", "DS"]}
df = pandas.DataFrame(data)


df.loc[lambda df : df["prenom"].str.startswith("A")]

  prenom poste
0   Anna    DE