# Rappels

In [1]:
import pandas
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df_titanic = pandas.read_csv(url)
df_titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
pandas.pivot_table(
    df_titanic, 
    index=["Sex", "Pclass"], 
    values="Survived")

               Survived
Sex    Pclass
female 1       0.978723
       2       0.952381
       3       0.476190
male   1       0.365079
       2       0.131148
       3       0.113300

In [7]:
# Noter que le résultat précédent est équivalent à 
df_titanic.groupby(["Sex", "Pclass"])["Survived"].mean()

Sex     Pclass
female  1         0.978723
        2         0.952381
        3         0.476190
male    1         0.365079
        2         0.131148
        3         0.113300
Name: Survived, dtype: float64

In [ ]:
pandas.pivot_table(df_titanic, 
                   index=["Sex", "Pclass"], 
                   columns="Survived", 
                   values="Fare")

Survived                0           1
Sex    Pclass
female 1       151.550000  108.111863
       2        14.833333   22.559375
       3        18.735419   12.399493
male   1        64.145829   56.150179
       2        21.662159   21.592708
       3        12.781865   15.648703

In [ ]:
# Noter l'utilisation des margins
pandas.pivot_table(df_titanic, 
                   index=["Sex", "Pclass"], 
                   columns="Survived", 
                   values="Fare", margins = True)

Survived                0           1         All
Sex    Pclass
female 1       110.604167  105.978159  106.125798
       2        18.250000   22.288989   21.970121
       3        19.773093   12.464526   16.118810
male   1        62.894910   74.637320   67.226127
       2        19.488965   21.095100   19.741782
       3        12.204469   15.579696   12.661633
All             22.117887   48.395408   32.204208

In [ ]:
pandas.pivot_table(df_titanic, index=["Sex"], columns="Survived", values=["SibSp", "Parch"])

             Parch               SibSp
Survived         0         1         0         1
Sex
female    1.085106  0.566176  1.021277  0.573529
male      0.242063  0.430769  0.547619  0.430769

In [ ]:
# Crosstab
pandas.crosstab(df_titanic.Sex, df_titanic.Survived)

Survived    0    1
Sex
female     45  134
male      263   58

### Exercices

In [3]:
# Proposer un dataframe pour connaître l'influence du lieu d'embarquement sur les chances de survie.
# On gardera Sex et Pclass comme index.

In [ ]:
# Bonus
# Proposer un dataframe pour confronter les lieux d'embarquement et les âges
# Exempel à ne pas suivre : 
pandas.pivot_table(df_titanic, index="Age", columns="Embarked", values="Survived")
# le tableau suivant est illisible. Il faut regrouper les âges avec la fonction cut

Embarked    C    Q    S
Age
0.42      1.0  NaN  NaN
0.67      NaN  NaN  1.0
0.75      1.0  NaN  NaN
0.83      NaN  NaN  1.0
0.92      NaN  NaN  1.0
...       ...  ...  ...
70.00     NaN  NaN  0.0
70.50     NaN  0.0  NaN
71.00     0.0  NaN  NaN
74.00     NaN  NaN  0.0
80.00     NaN  NaN  1.0

[88 rows x 3 columns]

In [ ]:
# On propose de créer des catégories d'âge

# fonction cut, qui permet de créer des groupes d'age

# il existe aussi la fonction qcut (quantile cut), qui permet de créer des groupes d'age de même taille

In [1]:
# nombre de représentants de chaque catégorie

In [2]:
# chances de survie par age et par lieu d'embarquement

In [ ]:
df_titanic["Age"].describe()
# Cela correspond aux groups qu'on obtiendrait avec la fonction qcut si on faisait 4 groupes